### ISSUE TITLE
Example doge.js <img> tag replacing not working on nodejs.org from 301 Redirect

### ISSUE THREAD

**Issue by nutterbrand** [No9/harmon#22]
The environment is running from http://localhost:8000.

doge.js is not working as expected from a 301 redirect. Harmon intercepts the response body of the 301 redirect instead of expected the response body from nodejs.org. This means the logo <img .. > image from nodejs.org is never replaced with dog picture from the example.

Is there a setting to node-http-proxy or in harmon to do the replacing on the response body from the response body of the end resulting page, for this example nodejs.org?

**Comment by No9** [comment]
Hi @nutterbrand 
Looks like nodejs.org now enforces https by returning a 301 for plain http requests.
 
The reason harmon doesn't replace the image is because the browser is now goes directly to the nodejs.org because of the redirect. 

I would suggest running it against a known http target 
There are ways around that in the proxy config but it is beyond the idea of the sample to get into that.

**Comment by No9** [comment]
Hi @nutterbrand  
Part of the question for #23 has the answer you are looking for.
Please see the working sample at the bottom of that issue. 

Thanks

**Comment by No9** [comment]
Ok I have just updated the doge.js example too so I am going to close this issue. 
https://github.com/No9/harmon/blob/master/examples/doge.js

**Comment by nutterbrand** [comment]
Thanks! This is perfect!
